spring.application.name=hotel

# ${NAME} è una variabile d'ambiente che viene passata da Render, se non è definita allora viene usata il valore di default

### Port
server.port: ${PORT:8081}

#spring data configuration
#${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/dbgester} se si usa MySQL in locale
spring.datasource.url=spring.datasource.url=jdbc:postgresql://${SPRING_DATASOURCE_HOSTNAME:localhost}:5432/dbgester
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Georez660#2001#10 #15}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


### Hibernate Properties
## The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect #se si usa MySQL
spring.jpa.hibernate.ddl-auto =update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
